[package]
name = "hydra-resolve"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
hydra-ast = { path = "../hydra-ast" }
hydra-diagnostics = { path = "../hydra-diagnostics" }
hydra-source = { path = "../hydra-source" }
hydra-stdlib = { path = "../hydra-stdlib" }

[dev-dependencies]
hydra-lexer = { path = "../hydra-lexer" }
hydra-parser = { path = "../hydra-parser" }

[lints]
workspace = true
