[package]
name = "hydra-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
hydra-diagnostics = { path = "../hydra-diagnostics" }
hydra-hir = { path = "../hydra-hir" }
hydra-resolve = { path = "../hydra-resolve" }
hydra-source = { path = "../hydra-source" }

[dev-dependencies]
hydra-types = { path = "../hydra-types" }

[lints]
workspace = true
